name: 'Benchmarking'

on: [pull_request]

jobs:
  benchmarking:
    runs-on: ubuntu-latest
    name: Benchmarking the generators

    steps:
      - uses: actions/checkout@v2
      - uses: JayaKrishnaNamburu/behchmark@master
        with:
          secret-token: "${{ secrets.BENCHMARK_TOKEN }}"
